### ISSUE TITLE
sql文件可能存在问题

### ISSUE THREAD

**Issue by pdd1996** [fabian4/FruitDay#1]
你好，我是初学者，使用你的sql文件出现错误，具体错误为utf8_general_ci
然后我试着使用网上提供的方案，始终无法解决

**Comment by fabian4** [comment]
可以具体提供一下报错的代码位置吗

**Comment by pdd1996** [comment]
你好，我目前使用的数据库工具如下

1. 数据库是**mysql**，版本是**5.7**
2. 管理数据库是**Navicat**，版本是**16.0.1.0**

目前运行 **fruit** sql文件出现
**[SQL] Finished with error**

运行结果只有两张表

1. fruits
2. hotfruits

我打开sql文件，将其代码运行，出现以下错误
**1273 - Unknown collation: 'utf8mb4_0900_ai_ci'**

我查阅google，按照其思路解决，但仍无法解决问题，希望获得作者帮助

**Comment by fabian4** [comment]
出现这样的问题是原sql文件是mysql（8.0版本），高级往低级（5.6版本）导入时出现版本不兼容的情况。

把文件中的所有的utf8mb4_0900_ai_ci替换为utf8_general_ci，以及utf8mb4替换为utf8

希望可以帮到你
